### ISSUE TITLE
Comment type is not supported... This file doesn't compile successfully

### ISSUE THREAD

**Issue by pencilcheck** [jozanza/jsonify-css#1]
https://unpkg.com/antd@2.7.4/dist/antd.css

I got this error while using your other plugins `next-css-json-loader` in a nextjs project
I tried to import this css into a component, then I get this error, which links back to this package.

```
Module build failed: Error: Could not transform CSS rule: {
  "type": "comment",
  "comment": "!\n * antd v2.7.4\n * \n * Copyright 2015-present, Alipay, Inc.\n * All rights reserved.\n ",
  "position": {
    "start": {
      "line": 1,
      "column": 1
    },
    "end": {
      "line": 6,
      "column": 4
    }
  }
}
    at /project/node_modules/jsonify-css/parse.js:8:11
    at x (/project/node_modules/jsonify-css/parse.js:14:17)
    at Array.map (native)
    at text (/project/node_modules/jsonify-css/parse.js:31:4)
    at Object.loader (/project/node_modules/next-css-json-loader/index.js:5:81)

 @ ./pages?entry 33:13-42
 @ multi ./~/next/dist/client/webpack-hot-middleware-client ./~/next/dist/client/on-demand-entries-client ./pages?entry
```

**Comment by jozanza** [comment]
Updated to ignore parsing for css comments: https://github.com/jozanza/jsonify-css/commit/225ec17ce746fb22aaa378ab9f03f83e0cbd4913

@pencilcheck if you update to version `0.0.3`, you should no longer have this issue.
